server {
    listen 80;
    server_name _;

    location / {
        root /usr/share/nginx/html;
        index index.html;
    }

    # Dùng để heal.sh và Prometheus kiểm tra sống/chết
    location /health {
        access_log off;
        default_type text/plain;
        return 200 "OK\n";
    }

    # Dùng để nginx-exporter lấy số liệu - chỉ cho phép nội bộ Docker network
    location /nginx_status {
        stub_status;
        allow 172.28.0.0/16;
        allow 127.0.0.1;
        deny all;
    }
}
